name: Unzip and Commit to Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  workflows: write   # âœ… allows updating workflow files

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Unzip .github.zip
      run: |
        unzip -o .github.zip
        echo "File unzipped successfully"
        
    - name: Commit all files to repository
      run: |
        git config --local user.email "bibekmondal906@gmail.com"
        git config --local user.name "radharadha777"
        git add .
        git commit -m "Add all unzipped files from reviactyl.zip" || echo "No changes to commit"
        git push
